services:
  - type: web
    name: echochamber-backend
    env: node
    branch: main #
    rootDir: . #
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: your_database_url_here
